FROM mcr.microsoft.com/mssql/server:2019-latest

# set environment variables
ENV SA_PASSWORD=Your!StrongPass
 
ENV ACCEPT_EULA=Y

# Create local sql directory
COPY docker/createdb.sql createdb.sql
COPY docker/setup.sh setup.sh
COPY docker/entry.sh entry.sh
#RUN chmod +x ./entry.sh
CMD /bin/bash ./entry.sh 




